"""first migration

Revision ID: 20c5729ad6dd
Revises: 
Create Date: 2024-08-05 17:27:27.185825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20c5729ad6dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.LargeBinary(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('role', sa.Enum('ARTIST', 'USER', 'ADMIN', 'GUEST', name='role'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('username', name=op.f('uq_user_username'))
    )
    op.create_table('album',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], name=op.f('fk_album_artist_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_album'))
    )
    op.create_table('song',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('genre', sa.Enum('ROCK', 'POP', 'JAZZ', 'CLASSICAL', 'HIPHOP', 'ELECTRONIC', 'REGGAE', 'BLUES', name='genre'), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['album.id'], name=op.f('fk_song_album_id_album')),
    sa.ForeignKeyConstraint(['artist_id'], ['user.id'], name=op.f('fk_song_artist_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_song'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song')
    op.drop_table('album')
    op.drop_table('user')
    # ### end Alembic commands ###