"""new migration

Revision ID: c88f0c9a5a78
Revises: 20c5729ad6dd
Create Date: 2024-08-07 09:32:33.045294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88f0c9a5a78'
down_revision: Union[str, None] = '20c5729ad6dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_album_name_artist_id'), 'album', ['name', 'artist_id'])
    op.alter_column('song', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_song_name_artist_id_album_id'), 'song', ['name', 'artist_id', 'album_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_song_name_artist_id_album_id'), 'song', type_='unique')
    op.alter_column('song', 'album_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('uq_album_name_artist_id'), 'album', type_='unique')
    # ### end Alembic commands ###