"""photo url and file url fields

Revision ID: 8e7d1f756715
Revises: c88f0c9a5a78
Create Date: 2024-08-07 14:02:49.913898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e7d1f756715'
down_revision: Union[str, None] = 'c88f0c9a5a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('file_url', sa.String(), nullable=False))
    op.add_column('song', sa.Column('photo_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'photo_url')
    op.drop_column('song', 'file_url')
    # ### end Alembic commands ###
    