"""Added photo_url field to the Album table

Revision ID: c34f48d36a0c
Revises: 8e7d1f756715
Create Date: 2024-08-09 14:24:06.125131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34f48d36a0c'
down_revision: Union[str, None] = '8e7d1f756715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album', sa.Column('photo_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('album', 'photo_url')
    # ### end Alembic commands ###